# Outlines the wordmark: `hansenexus` in Fraunces (the display face of @hansenexus/tokens),
# shaped with HarfBuzz and written as path data into packages/ui/src/brand-geometry.ts, next
# to the mark's polygons. Outlines, not live text, so the lockup looks the same everywhere,
# with or without the font. Run it only to change the wordmark; `bun run brand` does the rest.
# Run: uv run --with fonttools==4.60.2 --with brotli==1.1.0 --with uharfbuzz==0.51.1 \
#        python scripts/brand-outline.py && bunx biome check --write packages/ui/src/brand-geometry.ts
import io
import json
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "packages/ui/node_modules/@fontsource-variable/fraunces/files/fraunces-latin-full-normal.woff2"
OUT = ROOT / "packages/ui/src/brand-geometry.ts"

TEXT = "hansenexus"
# Semibold, a text optical size (sturdy hairlines at 20 to 40 px), no soft or wonky forms.
AXES = {"wght": 600, "opsz": 36, "SOFT": 0, "WONK": 0}

# The canonical mark: hansenexus/hn-monorepo apps/hansenexus/public/logo.svg, unchanged.
MARK_W, MARK_H = 422.64, 321.81
MARK_POLYGONS = [
    "309.72 0 246.7 99.12 105.15 321.81 0 321.81 204.56 0 309.72 0",
    "422.64 210.46 351.85 321.81 246.7 321.81 317.48 210.46 246.7 99.12 351.85 99.12 422.64 210.46",
]
# Space between the mark and the text, in mark heights.
GAP = 0.3


def r(v: float) -> str:
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return "0" if s == "-0" else s


def main() -> None:
    font = TTFont(FONT)
    static = instantiateVariableFont(font, AXES)
    static.flavor = None  # HarfBuzz reads sfnt, not WOFF2
    buf = io.BytesIO()
    static.save(buf)
    upm = static["head"].unitsPerEm

    hb_font = hb.Font(hb.Face(buf.getvalue()))
    shaped = hb.Buffer()
    shaped.add_str(TEXT)
    shaped.guess_segment_properties()
    hb.shape(hb_font, shaped, {"kern": True, "liga": False})

    glyphs = static.getGlyphSet()
    order = static.getGlyphOrder()
    placed = []
    x = 0
    for info, pos in zip(shaped.glyph_infos, shaped.glyph_positions):
        placed.append((order[info.codepoint], x + pos.x_offset, pos.y_offset))
        x += pos.x_advance

    bounds = BoundsPen(glyphs)
    for name, gx, gy in placed:
        glyphs[name].draw(TransformPen(bounds, (1, 0, 0, 1, gx, gy)))
    x_min, y_min, _x_max, y_max = bounds.bounds

    # The ascender of h is the mark's height; both stand on the baseline.
    s = MARK_H / y_max
    left = MARK_W + GAP * MARK_H
    pen = SVGPathPen(glyphs, ntos=r)
    for name, gx, gy in placed:
        # font units, y up -> lockup units, y down, baseline at MARK_H
        t = (s, 0, 0, -s, left + (gx - x_min) * s, MARK_H - gy * s)
        glyphs[name].draw(TransformPen(pen, t))
    width = left + (bounds.bounds[2] - x_min) * s
    height = MARK_H - y_min * s

    ts = f"""// The hansenexus mark and wordmark geometry. The mark is the canonical logo, unchanged
// (hansenexus/hn-monorepo apps/hansenexus/public/logo.svg); the wordmark is `{TEXT}` in
// Fraunces {AXES["wght"]}, opsz {AXES["opsz"]}, outlined. Generated by scripts/brand-outline.py; do not edit.
// The name, mark and wordmark are trademarks, not covered by the MIT licence (TRADEMARK.md).

/** The mark: two flat polygons. */
export const MARK = {{
  width: {r(MARK_W)},
  height: {r(MARK_H)},
  polygons: {json.dumps(MARK_POLYGONS, indent=4).replace("    ", "    ").replace("]", "  ]")},
}} as const;

/** The lockup: the mark at the origin, the outlined text after it on the same baseline. */
export const WORDMARK = {{
  width: {r(width)},
  height: {r(height)},
  /** Where the text starts; the mark fills 0..MARK.width. */
  textX: {r(left)},
  text: "{pen.getCommands()}",
}} as const;
"""
    OUT.write_text(ts)
    print(f"brand-outline: wrote {OUT.relative_to(ROOT)} (upm {upm}, {width:.1f} x {height:.1f})")


if __name__ == "__main__":
    main()
